import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './componets/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'nextjs mini project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
        <Header/>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
